import type { Metadata } from "next";
import { Breadcrumb } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Breadcrumb 
        items={
          [
            { title: 'Inicio', href: '/' },
            { title: 'Atividades', href: '/activities' },
          ]
        }
        />
        {children}
      </body>
    </html>
  );
}
